name: Run Docker

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3

      - name: Download docker image
        run: docker pull luizsenai2022/senai:latest

      - name: Remove all container
        run: docker container rm -f $(docker container ps -a -q) || echo "Nenhum container"

      - name: Run container
        run: docker run -d -p 8080:80 --name webserver luizsenai2022/senai:latest
