name: Build Docker

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 420787118342.dkr.ecr.us-east-1.amazonaws.com
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
